# Generated by Django 4.2.7 on 2023-11-10 06:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_channel_verified_alter_channel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_art',
            field=models.ImageField(blank=True, default='channel-art.jpg', null=True, upload_to=core.models.user_directory_path),
        ),
    ]
